// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Copyright: typeof import('./components/Copyright.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GameMap: typeof import('./components/GameMap.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    MatchGround: typeof import('./components/MatchGround.vue')['default']
    PlayGround: typeof import('./components/PlayGround.vue')['default']
    README: typeof import('./components/README.md')['default']
    ResultBoard: typeof import('./components/ResultBoard.vue')['default']
    ResultGround: typeof import('./components/ResultGround.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VAceEditor: typeof import('vue3-ace-editor')['VAceEditor']
  }
}
